name: Main

on: [ workflow_dispatch, push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: SetupNDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r24
    - name: Build
      run: |
        chmod 777 ./build.sh
        ./build.sh
    - name: Upload release
      uses: actions/upload-artifact@v3
      with:
        name: logcat-proc-monitor
        path: out/magisk-module
    - name: Build Zygisk
      run: sed -i "s/^FLAVOR=.*/FLAVOR=Zygisk/g" ./out/magisk-module/customize.sh
    - name: Upload Zygisk release
      uses: actions/upload-artifact@v3
      with:
        name: zygisk-proc-monitor
        path: out/magisk-module
